name: Build and publish Janet docker images

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: .docker/Dockerfile
          repository: leafgarland/janet
          tags: latest
          tag_with_ref: true
          add_git_labels: true
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: .docker/Dockerfile
          repository: leafgarland/janet-sdk
          target: dev
          tags: latest
          tag_with_ref: true
          add_git_labels: true

